### ISSUE TITLE
Java players' rotation is not sent to PE players unless they change position

### ISSUE THREAD

**Issue by AryToNeX** [ProtocolSupport/ProtocolSupportPocketIssues#16] opened 2018-07-06 02:52 UTC
Playing Minecraft is also looking at things while standing still, like when you chop a tree from bottom to top standing under the remaining log blocks. That is, Java players can move their head but other players on PE will see them facing the same direction unless they move. I am not sure if this can have problems with block placing/destroying

**Comment by magicus** [comment] 2018-11-25 16:48
I can confirm that this is still present as of today in mcpenew.

Also, it's (possibly) worse now; not only the head, but the entire body is not rotated until movement occurs.

**Comment by magicus** [comment] 2018-11-25 16:49
I cannot say if this happens when a PE player observes another PE player, since I have not been able to test this setup yes.

**Comment by colinrgodsey** [comment] 2019-01-13 00:36
fixed with caolis new changes (and my supplemental rotation fixes)

**Closed by colinrgodsey** 2019-01-13 00:36 UTC
Labels: PRIO: MEDIUM, bug, visual_glitch
